**
**	amitls_lib.i library vector offsets (LVOs)
**
**	For recreational and educational use only.
**	Some assembly required.
**	Use only if linking against amiga.lib is not a viable alternative.
**
**
**
**	Generated by LibDescConverter from an sfd file

**"amitls.library"
**--- functions in V1 or higher ---
** Tier 0 - Per-process TLS defaults (after OpenLibrary only).
** Bootstrap: OpenLibrary(AMITLSNAME, AMITLSVERSION) plus caller-owned
** bsdsocket.library (pass its base to TlsTaskAttach, like AmiSSL_SocketBase).
_LVOTlsBaseTagsA equ -30
_LVOTlsError equ -36
_LVOTlsGetErrorString equ -42
** Tier 1 - Per-task TLS runtime (call once per Exec task using TLS I/O).
** Caller must OpenLibrary("bsdsocket.library") and pass the base here.
_LVOTlsTaskAttach equ -48
_LVOTlsTaskDetach equ -54
** Tier 1 - TlsContext (verify policy, optional CA overrides).
** Pass NULL / TAG_DONE for defaults.
_LVONewTlsContextA equ -60
_LVODisposeTlsContext equ -66
_LVOSetTlsContextAttrsA equ -72
** Tier 2 - TlsConnection (attach TLS to an existing TCP socket).
_LVONewTlsConnection equ -78
_LVODisposeTlsConnection equ -84
_LVOTlsAttachSocketA equ -90
_LVOTlsRead equ -96
_LVOTlsWrite equ -102
_LVOTlsPending equ -108
_LVOTlsShutdown equ -114
_LVOTlsGetLastError equ -120
_LVOTlsGetCertVerifyDetail equ -126
_LVOTlsGetPeerCert equ -132
_LVOTlsPeerCertFree equ -138
** Tier 3 - Trust store.  Prefer ATBT/ATSA_CA_BUNDLE_PATH tags; no implicit
** default path.  TlsLoadCABundle() sets the library-base path (same as ATBT).
_LVOTlsLoadCABundle equ -144
_LVOTlsAddTrustedCert equ -150
_LVOTlsClearTrustedCerts equ -156
_LVOTlsHandshake equ -162

