#ifndef PRAGMA_AMITLS_LIB_H
#define PRAGMA_AMITLS_LIB_H

/*
** Aztec 'C', Maxon 'C' and StormC format pragma files
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_AMITLS_PROTOS_H
#include <clib/amitls_protos.h>
#endif /* CLIB_AMITLS_PROTOS_H */

/*"amitls.library" */
/*--- functions in V1 or higher --- */

/* Tier 0 - Per-process TLS defaults (after OpenLibrary only). */

/* Bootstrap: OpenLibrary(AMITLSNAME, AMITLSVERSION) plus caller-owned */
/* bsdsocket.library (pass its base to TlsTaskAttach, like AmiSSL_SocketBase). */

#pragma amicall(TlsBase, 0x1E, TlsBaseTagList(a0))
#pragma amicall(TlsBase, 0x24, TlsError())
#pragma amicall(TlsBase, 0x2A, TlsGetErrorString(d0))

/* Tier 1 - Per-task TLS runtime (call once per Exec task using TLS I/O). */
/* Caller must OpenLibrary("bsdsocket.library") and pass the base here. */

#pragma amicall(TlsBase, 0x30, TlsTaskAttach(a0,a1))
#pragma amicall(TlsBase, 0x36, TlsTaskDetach())

/* Tier 1 - TlsContext (verify policy, optional CA overrides). */

#pragma amicall(TlsBase, 0x3C, NewTlsContext(a0))
#pragma amicall(TlsBase, 0x42, DisposeTlsContext(a0))
#pragma amicall(TlsBase, 0x48, SetTlsContextAttrsA(a0,a1))

/* Tier 2 - TlsConnection (attach TLS to an existing TCP socket). */

#pragma amicall(TlsBase, 0x4E, NewTlsConnection(a0))
#pragma amicall(TlsBase, 0x54, DisposeTlsConnection(a0))
#pragma amicall(TlsBase, 0x5A, TlsAttachSocket(a0,d0,a1,a2))
#pragma amicall(TlsBase, 0x60, TlsRead(a0,a1,d0,d1))
#pragma amicall(TlsBase, 0x66, TlsWrite(a0,a1,d0))
#pragma amicall(TlsBase, 0x6C, TlsPending(a0))
#pragma amicall(TlsBase, 0x72, TlsShutdown(a0))
#pragma amicall(TlsBase, 0x78, TlsGetLastError(a0))
#pragma amicall(TlsBase, 0x7E, TlsGetCertVerifyDetail(a0))
#pragma amicall(TlsBase, 0x84, TlsGetPeerCert(a0,a1))
#pragma amicall(TlsBase, 0x8A, TlsPeerCertFree(a0))

/* Tier 3 - Trust store.  Prefer ATBT/ATSA_CA_BUNDLE_PATH tags; no implicit */
/* default path.  TlsLoadCABundle() sets the library-base path (same as ATBT). */

#pragma amicall(TlsBase, 0x90, TlsLoadCABundle(a0))
#pragma amicall(TlsBase, 0x96, TlsAddTrustedCert(a0,d0,d1))
#pragma amicall(TlsBase, 0x9C, TlsClearTrustedCerts())
#pragma amicall(TlsBase, 0xA2, TlsHandshake(a0,d0))

#endif /* PRAGMA_AMITLS_LIB_H */
