#ifndef PRAGMAS_AMITLS_PRAGMAS_H
#define PRAGMAS_AMITLS_PRAGMAS_H

/*
** Lattice 'C', Aztec 'C', SAS/C and DICE format pragma files.
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_AMITLS_PROTOS_H
#include <clib/amitls_protos.h>
#endif /* CLIB_AMITLS_PROTOS_H */

/*"amitls.library" */
/*--- functions in V1 or higher --- */

/* Tier 0 - Per-process TLS defaults (after OpenLibrary only). */

/* Bootstrap: OpenLibrary(AMITLSNAME, AMITLSVERSION) plus caller-owned */
/* bsdsocket.library (pass its base to TlsTaskAttach, like AmiSSL_SocketBase). */

#pragma libcall TlsBase TlsBaseTagList 1E 801
#pragma libcall TlsBase TlsError 24 00
#pragma libcall TlsBase TlsGetErrorString 2A 001

/* Tier 1 - Per-task TLS runtime (call once per Exec task using TLS I/O). */
/* Caller must OpenLibrary("bsdsocket.library") and pass the base here. */

#pragma libcall TlsBase TlsTaskAttach 30 9802
#pragma libcall TlsBase TlsTaskDetach 36 00

/* Tier 1 - TlsContext (verify policy, optional CA overrides). */

#pragma libcall TlsBase NewTlsContext 3C 801
#pragma libcall TlsBase DisposeTlsContext 42 801
#pragma libcall TlsBase SetTlsContextAttrsA 48 9802

/* Tier 2 - TlsConnection (attach TLS to an existing TCP socket). */

#pragma libcall TlsBase NewTlsConnection 4E 801
#pragma libcall TlsBase DisposeTlsConnection 54 801
#pragma libcall TlsBase TlsAttachSocket 5A A90804
#pragma libcall TlsBase TlsRead 60 109804
#pragma libcall TlsBase TlsWrite 66 09803
#pragma libcall TlsBase TlsPending 6C 801
#pragma libcall TlsBase TlsShutdown 72 801
#pragma libcall TlsBase TlsGetLastError 78 801
#pragma libcall TlsBase TlsGetCertVerifyDetail 7E 801
#pragma libcall TlsBase TlsGetPeerCert 84 9802
#pragma libcall TlsBase TlsPeerCertFree 8A 801

/* Tier 3 - Trust store.  Prefer ATBT/ATSA_CA_BUNDLE_PATH tags; no implicit */
/* default path.  TlsLoadCABundle() sets the library-base path (same as ATBT). */

#pragma libcall TlsBase TlsLoadCABundle 90 801
#pragma libcall TlsBase TlsAddTrustedCert 96 10803
#pragma libcall TlsBase TlsClearTrustedCerts 9C 00
#pragma libcall TlsBase TlsHandshake A2 0802

#endif /* PRAGMAS_AMITLS_PRAGMAS_H */
