#ifndef INLINE_AMITLS_H
#define INLINE_AMITLS_H

/*
** GCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/*"amitls.library" */
/*--- functions in V1 or higher --- */

/* Tier 0 - Per-process TLS defaults (after OpenLibrary only). */

/* Bootstrap: OpenLibrary(AMITLSNAME, AMITLSVERSION) plus caller-owned */
/* bsdsocket.library (pass its base to TlsTaskAttach, like AmiSSL_SocketBase). */

#define TlsBaseTagsA(tags)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TagItem *p0 __asm("a0") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-30:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define TlsBaseTags(vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	TlsBaseTagsA(_argarray);   \
	r;   \
})
#endif

#define TlsError()    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-36:W);" : "+r"(b), "=r"(r) :  : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define TlsGetErrorString(code)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register LONG p0 __asm("d0") = (code);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-42:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


/* Tier 1 - Per-task TLS runtime (call once per Exec task using TLS I/O). */
/* Caller must OpenLibrary("bsdsocket.library") and pass the base here. */

#define TlsTaskAttach(SocketBase, errno_ptr)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct Library *p0 __asm("a0") = (SocketBase);   \
	register APTR p1 __asm("a1") = (errno_ptr);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-48:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define TlsTaskDetach()    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	__asm volatile ("jsr a6@(-54:W);" : "+r"(b), "=r"(r) :  : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})


/* Tier 1 - TlsContext (verify policy, optional CA overrides). */
/* Pass NULL / TAG_DONE for defaults. */

#define NewTlsContextA(tags)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TagItem *p0 __asm("a0") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-60:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define NewTlsContext(vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	NewTlsContextA(_argarray);   \
	r;   \
})
#endif

#define DisposeTlsContext(ctx)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsContext *p0 __asm("a0") = (ctx);   \
	__asm volatile ("jsr a6@(-66:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define SetTlsContextAttrsA(ctx, tags)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsContext *p0 __asm("a0") = (ctx);   \
	register struct TagItem *p1 __asm("a1") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-72:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define SetTlsContextAttrs(ctx, vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	SetTlsContextAttrsA((ctx), _argarray);   \
	r;   \
})
#endif


/* Tier 2 - TlsConnection (attach TLS to an existing TCP socket). */

#define NewTlsConnection(ctx)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsContext *p0 __asm("a0") = (ctx);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-78:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DisposeTlsConnection(conn)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsConnection *p0 __asm("a0") = (conn);   \
	__asm volatile ("jsr a6@(-84:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define TlsAttachSocketA(conn, sock, hostname, tags)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsConnection *p0 __asm("a0") = (conn);   \
	register LONG p1 __asm("d0") = (sock);   \
	register STRPTR p2 __asm("a1") = (hostname);   \
	register struct TagItem *p3 __asm("a2") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-90:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define TlsAttachSocket(conn, sock, hostname, vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	TlsAttachSocketA((conn), (sock), (hostname), _argarray);   \
	r;   \
})
#endif

#define TlsRead(conn, buffer, buflen, timeout_secs)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsConnection *p0 __asm("a0") = (conn);   \
	register APTR p1 __asm("a1") = (buffer);   \
	register ULONG p2 __asm("d0") = (buflen);   \
	register ULONG p3 __asm("d1") = (timeout_secs);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-96:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define TlsWrite(conn, buffer, len)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsConnection *p0 __asm("a0") = (conn);   \
	register APTR p1 __asm("a1") = (buffer);   \
	register ULONG p2 __asm("d0") = (len);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-102:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define TlsPending(conn)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-108:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define TlsShutdown(conn)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-114:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define TlsGetLastError(conn)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-120:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define TlsGetCertVerifyDetail(conn)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-126:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define TlsGetPeerCert(conn, cert)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsConnection *p0 __asm("a0") = (conn);   \
	register struct TlsPeerCert *p1 __asm("a1") = (cert);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-132:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define TlsPeerCertFree(cert)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsPeerCert *p0 __asm("a0") = (cert);   \
	__asm volatile ("jsr a6@(-138:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})


/* Tier 3 - Trust store.  Prefer ATBT/ATSA_CA_BUNDLE_PATH tags; no implicit */
/* default path.  TlsLoadCABundle() sets the library-base path (same as ATBT). */

#define TlsLoadCABundle(path)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register STRPTR p0 __asm("a0") = (path);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-144:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define TlsAddTrustedCert(data, len, format)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register APTR p0 __asm("a0") = (data);   \
	register ULONG p1 __asm("d0") = (len);   \
	register ULONG p2 __asm("d1") = (format);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-150:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define TlsClearTrustedCerts()    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	__asm volatile ("jsr a6@(-156:W);" : "+r"(b), "=r"(r) :  : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define TlsHandshake(conn, timeout_secs)    \
({  \
	register void *b __asm("a6") = TlsBase;  \
	register struct TlsConnection *p0 __asm("a0") = (conn);   \
	register ULONG p1 __asm("d0") = (timeout_secs);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-162:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


#endif /* INLINE_AMITLS_H */
