#ifndef PROTO_AMITLS_H
#define PROTO_AMITLS_H

/*
** 'C' prototype and compiler specific header file combo
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef _NO_INLINE

#include <clib/amitls_protos.h>

#else

#ifndef __NOLIBBASE__


#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif /* EXEC_LIBRARIES_H */

extern struct Library * TlsBase;
#endif /* __NOLIBBASE__ */


#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_AMITLS_PRAGMAS_H
#include <pragmas/amitls_pragmas.h>
#endif /* PRAGMAS_AMITLS_PRAGMAS_H */


#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#ifndef PRAGMA_AMITLS_LIB_H
#include <pragma/amitls_lib.h>
#endif /* PRAGMA_AMITLS_LIB_H */

#elif defined(__VBCC__)

#include <clib/amitls_protos.h>

#ifndef INLINE_AMITLS_PROTOS_H
#include <inline/amitls_protos.h>
#endif /* INLINE_AMITLS_PROTOS_H */


#elif defined(__GNUC__)

#if defined(mc68000)
#ifndef INLINE_AMITLS_H
#include <inline/amitls.h>
#endif /* INLINE_AMITLS_H */
#else
#include <clib/amitls_protos.h>
#endif /* mc68000 */


/* Any other compiler */
#else

#include <clib/amitls_protos.h>


#endif /* __GNUC__ */


#endif /* _NO_INLINE */

#endif /* PROTO_AMITLS_H */
