#ifndef PROTO_AMITLS_H
#define PROTO_AMITLS_H

/*
** 'C' prototype and compiler specific header file combo
**
** Generated by LibDescConverter from an sfd file.
*/

#include <clib/amitls_protos.h>

#ifndef _NO_INLINE

#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_AMITLS_PRAGMAS_H
#include <pragmas/amitls_pragmas.h>
#endif /* PRAGMAS_AMITLS_PRAGMAS_H */

#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#ifndef PRAGMA_AMITLS_LIB_H
#include <pragma/amitls_lib.h>
#endif /* PRAGMA_AMITLS_LIB_H */

#elif defined(__VBCC__)

#ifndef INLINE_AMITLS_PROTOS_H
#include <inline/amitls_protos.h>
#endif /* INLINE_AMITLS_PROTOS_H */

#elif defined(__GNUC__)

#if defined(mc68000)
# ifdef __AROS__
#  include <defines/amitls.h>
# else
#  ifndef INLINE_AMITLS_H
#   include <inline/amitls.h>
#  endif /* INLINE_AMITLS_H */
# endif /* __AROS__ */
#endif /* mc68000 */

#endif /* compiler */

#endif /* _NO_INLINE */

#ifndef __NOLIBBASE__
  extern struct Library *
# ifdef __CONSTLIBBASEDECL__
   __CONSTLIBBASEDECL__
# endif /* __CONSTLIBBASEDECL__ */
  TlsBase;
#endif /* __NOLIBBASE__ */

#endif /* PROTO_AMITLS_H */
