#ifndef INLINE_AMITLS_PROTOS_H
#define INLINE_AMITLS_PROTOS_H

/*
** VBCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/*"amitls.library" */
/*--- functions in V1 or higher --- */

/* Tier 0 - Per-process TLS defaults (after OpenLibrary only). */

/* Bootstrap: OpenLibrary(AMITLSNAME, AMITLSVERSION) plus caller-owned */
/* bsdsocket.library (pass its base to TlsTaskAttach, like AmiSSL_SocketBase). */

LONG __TlsBaseTagList(__reg("a6") void *, __reg("a0") struct TagItem *tags)="\tjsr\t-30(a6)";
#define TlsBaseTagList(tags) __TlsBaseTagList(TlsBase, (tags))

LONG __TlsError(__reg("a6") void *)="\tjsr\t-36(a6)";
#define TlsError() __TlsError(TlsBase)

STRPTR __TlsGetErrorString(__reg("a6") void *, __reg("d0") LONG code)="\tjsr\t-42(a6)";
#define TlsGetErrorString(code) __TlsGetErrorString(TlsBase, (code))


/* Tier 1 - Per-task TLS runtime (call once per Exec task using TLS I/O). */
/* Caller must OpenLibrary("bsdsocket.library") and pass the base here. */

LONG __TlsTaskAttach(__reg("a6") void *, __reg("a0") struct Library *SocketBase, __reg("a1") APTR errno_ptr)="\tjsr\t-48(a6)";
#define TlsTaskAttach(SocketBase, errno_ptr) __TlsTaskAttach(TlsBase, (SocketBase), (errno_ptr))

void __TlsTaskDetach(__reg("a6") void *)="\tjsr\t-54(a6)";
#define TlsTaskDetach() __TlsTaskDetach(TlsBase)


/* Tier 1 - TlsContext (verify policy, optional CA overrides). */

struct TlsContext *__NewTlsContext(__reg("a6") void *, __reg("a0") struct TagItem *tags)="\tjsr\t-60(a6)";
#define NewTlsContext(tags) __NewTlsContext(TlsBase, (tags))

void __DisposeTlsContext(__reg("a6") void *, __reg("a0") struct TlsContext *ctx)="\tjsr\t-66(a6)";
#define DisposeTlsContext(ctx) __DisposeTlsContext(TlsBase, (ctx))

LONG __SetTlsContextAttrsA(__reg("a6") void *, __reg("a0") struct TlsContext *ctx, __reg("a1") struct TagItem *tags)="\tjsr\t-72(a6)";
#define SetTlsContextAttrsA(ctx, tags) __SetTlsContextAttrsA(TlsBase, (ctx), (tags))


/* Tier 2 - TlsConnection (attach TLS to an existing TCP socket). */

struct TlsConnection *__NewTlsConnection(__reg("a6") void *, __reg("a0") struct TlsContext *ctx)="\tjsr\t-78(a6)";
#define NewTlsConnection(ctx) __NewTlsConnection(TlsBase, (ctx))

void __DisposeTlsConnection(__reg("a6") void *, __reg("a0") struct TlsConnection *conn)="\tjsr\t-84(a6)";
#define DisposeTlsConnection(conn) __DisposeTlsConnection(TlsBase, (conn))

LONG __TlsAttachSocket(__reg("a6") void *, __reg("a0") struct TlsConnection *conn, __reg("d0") LONG sock, __reg("a1") STRPTR hostname, __reg("a2") struct TagItem *tags)="\tjsr\t-90(a6)";
#define TlsAttachSocket(conn, sock, hostname, tags) __TlsAttachSocket(TlsBase, (conn), (sock), (hostname), (tags))

LONG __TlsRead(__reg("a6") void *, __reg("a0") struct TlsConnection *conn, __reg("a1") APTR buffer, __reg("d0") ULONG buflen, __reg("d1") ULONG timeout_secs)="\tjsr\t-96(a6)";
#define TlsRead(conn, buffer, buflen, timeout_secs) __TlsRead(TlsBase, (conn), (buffer), (buflen), (timeout_secs))

LONG __TlsWrite(__reg("a6") void *, __reg("a0") struct TlsConnection *conn, __reg("a1") APTR buffer, __reg("d0") ULONG len)="\tjsr\t-102(a6)";
#define TlsWrite(conn, buffer, len) __TlsWrite(TlsBase, (conn), (buffer), (len))

ULONG __TlsPending(__reg("a6") void *, __reg("a0") struct TlsConnection *conn)="\tjsr\t-108(a6)";
#define TlsPending(conn) __TlsPending(TlsBase, (conn))

LONG __TlsShutdown(__reg("a6") void *, __reg("a0") struct TlsConnection *conn)="\tjsr\t-114(a6)";
#define TlsShutdown(conn) __TlsShutdown(TlsBase, (conn))

LONG __TlsGetLastError(__reg("a6") void *, __reg("a0") struct TlsConnection *conn)="\tjsr\t-120(a6)";
#define TlsGetLastError(conn) __TlsGetLastError(TlsBase, (conn))

LONG __TlsGetCertVerifyDetail(__reg("a6") void *, __reg("a0") struct TlsConnection *conn)="\tjsr\t-126(a6)";
#define TlsGetCertVerifyDetail(conn) __TlsGetCertVerifyDetail(TlsBase, (conn))

LONG __TlsGetPeerCert(__reg("a6") void *, __reg("a0") struct TlsConnection *conn, __reg("a1") struct TlsPeerCert *cert)="\tjsr\t-132(a6)";
#define TlsGetPeerCert(conn, cert) __TlsGetPeerCert(TlsBase, (conn), (cert))

void __TlsPeerCertFree(__reg("a6") void *, __reg("a0") struct TlsPeerCert *cert)="\tjsr\t-138(a6)";
#define TlsPeerCertFree(cert) __TlsPeerCertFree(TlsBase, (cert))


/* Tier 3 - Trust store.  Prefer ATBT/ATSA_CA_BUNDLE_PATH tags; no implicit */
/* default path.  TlsLoadCABundle() sets the library-base path (same as ATBT). */

LONG __TlsLoadCABundle(__reg("a6") void *, __reg("a0") STRPTR path)="\tjsr\t-144(a6)";
#define TlsLoadCABundle(path) __TlsLoadCABundle(TlsBase, (path))

LONG __TlsAddTrustedCert(__reg("a6") void *, __reg("a0") APTR data, __reg("d0") ULONG len, __reg("d1") ULONG format)="\tjsr\t-150(a6)";
#define TlsAddTrustedCert(data, len, format) __TlsAddTrustedCert(TlsBase, (data), (len), (format))

void __TlsClearTrustedCerts(__reg("a6") void *)="\tjsr\t-156(a6)";
#define TlsClearTrustedCerts() __TlsClearTrustedCerts(TlsBase)

LONG __TlsHandshake(__reg("a6") void *, __reg("a0") struct TlsConnection *conn, __reg("d0") ULONG timeout_secs)="\tjsr\t-162(a6)";
#define TlsHandshake(conn, timeout_secs) __TlsHandshake(TlsBase, (conn), (timeout_secs))


#endif /* INLINE_AMITLS_PROTOS_H */
