#ifndef CLIB_AMITLS_PROTOS_H
#define CLIB_AMITLS_PROTOS_H

/*
** 'C' prototypes. For use with 32 bit integers only.
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef LIBRARIES_AMITLS_H
#include <libraries/amitls.h>
#endif

/*"amitls.library"*/
/*--- functions in V1 or higher ---*/

/* Tier 0 - Per-process TLS defaults (after OpenLibrary only).*/

/* Bootstrap: OpenLibrary(AMITLSNAME, AMITLSVERSION) plus caller-owned*/
/* bsdsocket.library (pass its base to TlsTaskAttach, like AmiSSL_SocketBase).*/

LONG TlsBaseTagList(struct TagItem *tags);
LONG TlsError(void);
STRPTR TlsGetErrorString(LONG code);

/* Tier 1 - Per-task TLS runtime (call once per Exec task using TLS I/O).*/
/* Caller must OpenLibrary("bsdsocket.library") and pass the base here.*/

LONG TlsTaskAttach(struct Library *SocketBase, APTR errno_ptr);
void TlsTaskDetach(void);

/* Tier 1 - TlsContext (verify policy, optional CA overrides).*/

struct TlsContext *NewTlsContext(struct TagItem *tags);
void DisposeTlsContext(struct TlsContext *ctx);
LONG SetTlsContextAttrsA(struct TlsContext *ctx, struct TagItem *tags);

/* Tier 2 - TlsConnection (attach TLS to an existing TCP socket).*/

struct TlsConnection *NewTlsConnection(struct TlsContext *ctx);
void DisposeTlsConnection(struct TlsConnection *conn);
LONG TlsAttachSocket(struct TlsConnection *conn, LONG sock, STRPTR hostname, struct TagItem *tags);
LONG TlsRead(struct TlsConnection *conn, APTR buffer, ULONG buflen, ULONG timeout_secs);
LONG TlsWrite(struct TlsConnection *conn, APTR buffer, ULONG len);
ULONG TlsPending(struct TlsConnection *conn);
LONG TlsShutdown(struct TlsConnection *conn);
LONG TlsGetLastError(struct TlsConnection *conn);
LONG TlsGetCertVerifyDetail(struct TlsConnection *conn);
LONG TlsGetPeerCert(struct TlsConnection *conn, struct TlsPeerCert *cert);
void TlsPeerCertFree(struct TlsPeerCert *cert);

/* Tier 3 - Trust store.  Prefer ATBT/ATSA_CA_BUNDLE_PATH tags; no implicit*/
/* default path.  TlsLoadCABundle() sets the library-base path (same as ATBT).*/

LONG TlsLoadCABundle(STRPTR path);
LONG TlsAddTrustedCert(APTR data, ULONG len, ULONG format);
void TlsClearTrustedCerts(void);
LONG TlsHandshake(struct TlsConnection *conn, ULONG timeout_secs);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CLIB_AMITLS_PROTOS_H */
